baseURL = 'http://mbblog.io/'
languageCode = 'en-US'
title = 'mbblog.io'
DefaultContentLanguage = "en"
theme = "PaperMod"

enableRobotsTXT = true

[languages]
  [languages.en]
    disabled = false
    weight = 1
    contentDir = "content"
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    [languages.en.params]
      [languages.en.params.profileMode]
        enabled = true
        title = 'mbblog.io'
        subtitle = 'This page is currently under construction'

[params]
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  disableScrollToTop = false
  env = 'production'
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/mbblog"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'IT'
    url = 'https://it.mbblog.io'
    weight = 20
