baseURL = 'http://mbblog.io/'
languageCode = 'en-US'
title = 'mbblog.io'
DefaultContentLanguage = "en"
theme = "PaperMod"

[languages]
  [languages.en]
    disabled = false
    weight = 1
    contentDir = "content"
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    [languages.en.params]
      [languages.en.params.profileMode]
        enabled = true
        title = 'mbblog.io'
        subtitle = 'This page is currently under construction'

[params]
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  disableScrollToTop = false
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/mbblog"
